In [3]:
companies = ("amazon", "birla", "tesla", "wallmart", "concenrix")
type (companies)

tuple

In [4]:
print (companies[0:3])

('amazon', 'birla', 'tesla')

In [5]:
companies2 = list(companies)
companies2.append("TATA")
companies = tuple(companies2)
companies

('amazon', 'birla', 'tesla', 'wallmart', 'concenrix', 'TATA')

In [6]:
companies2 = list(companies)   
companies2[3] = "reliance" 
companies = tuple(companies2)
companies

('amazon', 'birla', 'tesla', 'reliance', 'concenrix', 'TATA')

In [7]:
companies = ('amazon', 'birla', 'tesla', 'reliance', 'concenrix', 'TATA')
(Delhi, Gurugtam, New_York, Mumbai, NCR, Gujrat)= companies
print (New_York)
print (NCR)

tesla
concenrix

In [8]:
companies = ('amazon', 'birla', 'tesla', 'reliance', 'concenrix', 'TATA')
(Delhi, Gurugtam, New_York, *Mumbai)= companies
print (New_York)
print (Mumbai)

tesla
['reliance', 'concenrix', 'TATA']

In [9]:
for x in companies:
    print (x)

amazon
birla
tesla
reliance
concenrix
TATA

In [10]:
""" Dictonary"""

' Dictonary'

In [11]:
employee = {
    "fname" : "Hifzur",
    "lname" : "Malik",
    "age"   : 20,
    "emp_ID" : 1
}
print (employee["emp_ID"])
print (employee["fname"])

1
Hifzur

In [12]:
len(employee)

4

In [13]:
student = {
    "name" : "Ahad",
    "age"  : 25,
    "married" : False,
    "city" : "Bareilly",
    "Region" : "India",
    "Degree" : {
        "d1" : "btech",
        "d2" : "mtech",
        "d3" : "phd"
    }
}
student

{'name': 'Ahad',
 'age': 25,
 'married': False,
 'city': 'Bareilly',
 'Region': 'India',
 'Degree': {'d1': 'btech', 'd2': 'mtech', 'd3': 'phd'}}

In [14]:
type(student)
print(student["Degree"]["d2"])

mtech

In [15]:
myvar = dict(f_name = "Akash", l_name = "Verma", age = 30, city = "Bareilly")
print (myvar)

{'f_name': 'Akash', 'l_name': 'Verma', 'age': 30, 'city': 'Bareilly'}

In [16]:
def add():
    print("Good Afternoon")

add()

Good Afternoon

In [17]:
def add(x,y):
    print (x + y)

def sub(x,y,z):
    print ((x*y)/z)

add (20,20)
sub (4,4,2)

40
8.0

In [18]:
def my_function (*cars):
    print ("the model of car: " + cars [3])

my_function ("ford", "tata", "toyota", "bmw")

the model of car: bmw

In [19]:
def my_car(**car):
    print("the model of car is " + car ["Model"])

my_car(co = "tata", Model = "harrier", color = "black")

the model of car is harrier

In [20]:
def my_bike (**bike):
    print("the model of my bike is " + bike ["Model"])

my_bike (company = "Royal Enfield", Model = "Hunter", color = "Black", cc = 350)

the model of my bike is Hunter

In [21]:
def city(ci ="bareilly"):
    print ("I lives in " + ci)

city ("Agra")
city ()

I lives in Agra
I lives in bareilly

In [22]:
def check_login(user, password, number, email):
    if user == "hifzmalik" or number == "1234567890" or email == "1234hifz@example" and password == "012345":
        return "login"
    else:
        return "wrong id and password"

user = input("enter user name:")
number = input("enter mobile number")
email = input ("enter email id")
passowrd = input ("enter password")

print(check_login(user, password, number, email))

enter user name: jffe
enter mobile number feke
enter email id 012345
enter password 012345

NameError: name 'password' is not defined

In [ ]:
def check_login(user, password, number, email):
    if user == "hifzmalik" or number == "1234567890" or email == "1234hifz@example" and password == "012345":
        return "login"
    else:
        return "wrong id and password"

user = input("enter user name")
number = input("enter mobile number")
email = input("enter email id")
password = input("enter password")  # Fixed typo in variable name 'passowrd'

print(check_login(user, password, number, email))

In [ ]:
import pandas as pd
hm = pd.read_csv("data2.csv")
print (hm)

In [ ]:
import pandas as pd

df = pd.read_csv('data2.csv')

df['Date'] = pd.to_datetime(df['Date'], format='mixed')

print(df.to_string())

In [ ]:
df.dropna(subset=['Date'], inplace = True)

In [ ]:
print(df.to_string())

In [24]:
import pandas as pd
data1 = pd.Series([1,2,3,4,5])
print (data1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [29]:
data2 = pd.Series([1,3,5,7,9], index = ["A", "B", "C", "D", "E"], dtype = float, name = "Python Data")
data2

A    1.0
B    3.0
C    5.0
D    7.0
E    9.0
Name: Python Data, dtype: float64

In [38]:
dic = {"Names": ["Ajay", "Rahul", "Vijay", "Raj"],"age": [20, 23, 30, 26], "city": ["Delhi", "Bareilly", "Goa", "Mumbai"]}
print (dic)

{'Names': ['Ajay', 'Rahul', 'Vijay', 'Raj'], 'age': [20, 23, 30, 26], 'city': ['Delhi', 'Bareilly', 'Goa', 'Mumbai']}

In [42]:
dic ={"Names":["Ajay", "Rahul", "Vijay", "Raj"],"age":[20, 23, 30, 26],"city":["Delhi", "Bareilly", "Goa", "Mumbai"]}
ser1=pd.Series(dic)
print (dic)

{'Names': ['Ajay', 'Rahul', 'Vijay', 'Raj'], 'age': [20, 23, 30, 26], 'city': ['Delhi', 'Bareilly', 'Goa', 'Mumbai']}

In [40]:
dic1={11:[34,23,23],12:[20,45,89],31:[2,5,7]}
ser2=pd.Series(dic1)
print(ser2)

11    [34, 23, 23]
12    [20, 45, 89]
31       [2, 5, 7]
dtype: object

In [41]:
dic={"sub":["phy","chem","math"],"marks":[20,45,89],"rank":[2,5,7]}
ser1=pd.Series(dic)
print(ser1)

sub      [phy, chem, math]
marks         [20, 45, 89]
rank             [2, 5, 7]
dtype: object

In [44]:
dic={12:[20,23,25], 15:[5,8,0],17:[11.14,16]}
ser2=pd.Series(dic1)
print(ser2)

11    [34, 23, 23]
12    [20, 45, 89]
31       [2, 5, 7]
dtype: object

In [45]:
hm = pd.Series(34,index=[1,2,3,4,5,6])
hm

1    34
2    34
3    34
4    34
5    34
6    34
dtype: int64

In [48]:
code=pd.Series(12,index=[1,2,3,4,5])
code2=pd.Series(15,index=[5,6,7,8,9])
print (code)
print (code2)
print (code+code2)

1    12
2    12
3    12
4    12
5    12
dtype: int64
5    15
6    15
7    15
8    15
9    15
dtype: int64
1     NaN
2     NaN
3     NaN
4     NaN
5    27.0
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64

In [50]:
code1=pd.Series(12,index=[1,2,3,4,5,6,7])
code2=pd.Series(12,index=[1,8,9,10,5,12,])
print (code1 + code2)

1     24.0
2      NaN
3      NaN
4      NaN
5     24.0
6      NaN
7      NaN
8      NaN
9      NaN
10     NaN
12     NaN
dtype: float64

In [51]:
# Data Frame

In [52]:
df= {"a": [1,2,4,6,8], "a2": [9,3,5,6,7], "a3": [2,5,7,8,4]}
data1=pd.DataFrame(df)
print (data1)

   a  a2  a3
0  1   9   2
1  2   3   5
2  4   5   7
3  6   6   8
4  8   7   4

In [65]:

l2={"a":[1,2,4,6],"s":[4,6,8,9],"d":[2,3,5,6]}

data2=pd.DataFrame(l2,columns=["a","d"],index=["a","s","d","f"])
# data2=pd.DataFrame(l2,columns=["a","d"],index=[1,3,4,5])
print(data2)
print(type(data2))

   a  d
a  1  2
s  2  3
d  4  5
f  6  6
<class 'pandas.core.frame.DataFrame'>

In [66]:
list= [[2,3,4], [3,5,6], [2,9,8]]
df=pd.DataFrame(list)
print (df)

   0  1  2
0  2  3  4
1  3  5  6
2  2  9  8

s1={"a":pd.Series([4,2,9,6]),"b":pd.Series([2,9,5,3])}
data2=pd.DataFrame(s1)
print(data2)
print("data:",data2["a"][2])

In [68]:
s1={"a":pd.Series([4,2,9,6]),"b":pd.Series([2,9,5,3])}
data2=pd.DataFrame(s1)
print(data2)
print("data:",data2["a"][2])

   a  b
0  4  2
1  2  9
2  9  5
3  6  3
data: 9

In [ ]:
# Arithmetic operation in DataFrame

In [69]:
d4= pd.DataFrame({"a": [1,2,4,6], "s": [4,6,8,9], "d": [2,3,5,6]})
print (d4)

   a  s  d
0  1  4  2
1  2  6  3
2  4  8  5
3  6  9  6

In [71]:
d4["Multiply"]= d4["s"]*d4["d"]
d4["Multiply>20"]=d4["Multiply"]>20
d4

   a  s  d  Multiply  Multiply>20
0  1  4  2         8        False
1  2  6  3        18        False
2  4  8  5        40         True
3  6  9  6        54         True

In [72]:
d4["Sum"]=d4["a"]+d4["s"]+d4["d"]
d4
d4["Diff(a-b)"]=d4["a"]-d4["s"]
d4
d4["Mul(a*b)"]=d4["a"]*d4["s"]
d4
d4["Div(a/b)"]=d4["a"]/d4["s"]
d4

   a  s  d  Multiply  Multiply>20  Sum  Diff(a-b)  Mul(a*b)  Div(a/b)
0  1  4  2         8        False    7         -3         4  0.250000
1  2  6  3        18        False   11         -4        12  0.333333
2  4  8  5        40         True   17         -4        32  0.500000
3  6  9  6        54         True   21         -3        54  0.666667

In [73]:
# Insert and Delete Data

In [74]:
l1={"a":[1,2,4,6],"s":[4,6,8,9],"d":[2,3,5,6]}

data1=pd.DataFrame(l1)
data1.insert(2,"Data1",data1["s"])
# data1.insert(1,"Data1",data1["s"])
print(data1)

   a  s  Data1  d
0  1  4      4  2
1  2  6      6  3
2  4  8      8  5
3  6  9      9  6

In [75]:
l1={"a":[1,2,4,6],"s":[4,6,8,9],"d":[2,3,5,6]}
data1=pd.DataFrame(l1)
data1.insert(1,"Data1",[4,6,7,8])
print(data1)

   a  Data1  s  d
0  1      4  4  2
1  2      6  6  3
2  4      7  8  5
3  6      8  9  6

In [76]:
data1["new"]=data1["s"][1:2]
data1
data1.pop("a")

0    1
1    2
2    4
3    6
Name: a, dtype: int64

In [77]:
# data1["new"]=data1["s"][:2]
# data1

In [78]:
data1.pop("s")
data1

   Data1  d  new
0      4  2  NaN
1      6  3  6.0
2      7  5  NaN
3      8  6  NaN

In [79]:
del data1["d"]
data1

   Data1  new
0      4  NaN
1      6  6.0
2      7  NaN
3      8  NaN